CREATE database inventario;
use inventario;
-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 13:09:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cat_marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`cat_marcas` (
  `id` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `marca_UNIQUE` (`marca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cat_ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`cat_ubicacion` (
  `id` INT NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ubicacion_UNIQUE` (`ubicacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventario`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_inventario` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(45) NOT NULL,
  `marca` INT NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `precio` DECIMAL(45) NOT NULL,
  `num_factura` INT NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  `num_serie` VARCHAR(45) NOT NULL,
  `ubicación` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_inventario_UNIQUE` (`num_inventario` ASC) VISIBLE,
  INDEX `marca_id_idx` (`marca` ASC) VISIBLE,
  INDEX `id_ubicacion_idx` (`ubicación` ASC) VISIBLE,
  CONSTRAINT `marca_id`
    FOREIGN KEY (`marca`)
    REFERENCES `inventario`.`cat_marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_ubicacion`
    FOREIGN KEY (`ubicación`)
    REFERENCES `inventario`.`cat_ubicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
